services:
  - type: web
    name: voxxy-presents-client
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SITE_URL
        value: https://www.voxxypresents.com
      - key: VITE_SITE_NAME
        value: "Voxxy Presents"
      - key: VITE_SITE_DESCRIPTION
        value: "Welcome to Voxxy Presents"
    domains:
      - www.voxxypresents.com
      - voxxypresents.com
    autoDeploy: true
    branch: main
    rootDir: .
    
  # Staging environment
  - type: web
    name: voxxy-presents-client-staging
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_ENVIRONMENT
        value: staging
      - key: VITE_API_BASE_URL
        value: https://voxxy-presents-api-staging.run.app/api
      - key: VITE_SITE_URL
        value: https://voxxy-presents-client-staging.onrender.com
      - key: VITE_SITE_NAME
        value: "Voxxy Presents (Staging)"
      - key: VITE_SITE_DESCRIPTION
        value: "Voxxy Presents Staging Environment"
    autoDeploy: true
    branch: staging
    rootDir: .

  # Development environment
  - type: web
    name: voxxy-presents-client-dev
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SITE_URL
        value: https://dev-voxxy-presents.onrender.com
      - key: VITE_SITE_NAME
        value: "Voxxy Presents (Dev)"
      - key: VITE_SITE_DESCRIPTION
        value: "Voxxy Presents Development Environment"
    autoDeploy: true
    branch: develop
    rootDir: .